services:
  - type: web
    name: vizrr
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
