services:
  - type: web
    name: keprates
    runtime: node
    region: singapore
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLIENT_ORIGIN
        value: https://www.keprates.in,https://keprates.in
